### ISSUE TITLE
Filtering duplicates from primary impacts performance

### ISSUE THREAD

**Issue by mgdenno** [RTIInternational/teehr#84]
These lines from `get_metrics()` look to negatively impact performance pretty significantly, esp. when the query has filters applied.  Guessing it forces a read of the entire primary dataset even when only some of it is needed.

```
WITH filtered_primary AS (
    SELECT * FROM(
        SELECT *,
            row_number()
        OVER(
            PARTITION BY value_time, location_id
            ORDER BY reference_time desc
            ) AS rn
        FROM read_parquet("/home/jovyan/data/protocols/retro/timeseries/usgs/*.parquet")
        )
),
```

34 seconds vs 4 seconds when filtering 3 years of retrospective data at all USGS stations to a single USGS station.

We might need a flag to only include this when the user requests that the primary data be "de-duped".

**Comment by samlamont** [comment]
@mgdenno I pushed some commits adding this flag to [this branch](https://github.com/RTIInternational/teehr/tree/84-filtering-duplicates-from-primary-impacts-performance).  Wondering how you want to handle the versioning since we'll be at v0.2.9 when #92 is merged.  

I could tack this de-dupe flag on to #92 or add a pre-release version here (ie, v.0.2.9.beta)? Any preference?

Weirdly I didn't see much impact of removing duplicates on query performance when testing against Katie's 2023 Hilary dataset (locally).  Not sure if I'm missing something or the dataset is too small to make a difference but just wanted to make a note

**Comment by mgdenno** [comment]
I think going to v0.2.10 is perfectly valid.

**Comment by mgdenno** [comment]
Just a note, we determined that filtering duplicates after the join is much faster, so the code snip looks like this:
```
, windowed AS (
            SELECT * FROM(
                SELECT *,
                    row_number() OVER(PARTITION BY value_time, primary_location_id, configuration ORDER BY reference_time desc) AS rn
                FROM joined
                ) t
            WHERE rn = 1
        )
        , metrics AS (
            SELECT
                joined.primary_location_id,joined.configuration
                , sum(primary_value - secondary_value)/count(*) as bias
            FROM
                windowed as joined
            GROUP BY
                joined.primary_location_id,joined.configuration
        )
```
